apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: default
  labels:
    app: nodec
    type: application
spec:
  type: NodePort
  selector:
    app: nodec
    type: application
  ports:
    - name: app-port
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: default
  labels:
    app: nodec
    type: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodec
      type: application
  strategy:
    rollingUpdate:
      maxSurge: 1 # 許容するPod追加数
      maxUnavailable: 1 # 許容するPod削除数
    type: RollingUpdate
  revisionHistoryLimit: 14
  template:
    metadata:
      name: nodeapp
      namespace: default
      labels:
        app: nodec
        type: application
    spec:
      containers:
      - name: node
        image: asia.gcr.io/gihyo-kube-303506/nodec-app:v1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: "MONGODB_HOSTS"
          value: "mongo-0.db-svc:27017,mongo-1.db-svc:27017,mongo-2.db-svc:27017"
        - name: "MONGODB_DATABASE"
          value: "nodec"
        - name: "MONGODB_REPLICASET"
          value: "rs0"
