version: "3"
services:
  mongod001:
    container_name: mongo-0
    image: mongo:4.0.5
    command: mongod --replSet rs0
    ports:
      - "30001:27017"
  mongod002:
    container_name: mongo-1
    image: mongo:4.0.5
    command: mongod --replSet rs0
    ports:
      - "30002:27017"
  mongod003:
    container_name: mongo-2
    image: mongo:4.0.5
    command: mongod --replSet rs0
    ports:
      - "30003:27017"
#  mongoa001:
#    container_name: mongoa001
#    image: mongo:4.0.5
#    command: mongod --replSet rs0
#    ports:
#      - "30004:27017"
