apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    app: nodec
spec:
  ports:
    - port: 27017
      name: mongo
  clusterIP: None
  selector:
    app: nodec

---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: ssd
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: nodec
spec:
  selector:
    matchLabels:
      app: nodec
  serviceName: db-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: nodec
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: Always
          args:
            - mongod
            - "--replSet"
            - rs0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        storageClassName: ssd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi